import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bgGradient w-screen h-screen overflow-hidden'>
        <div className='w-[100rem] mx-auto'>
        <Navbar textColor={`text-white`}/>
          {children}
        </div>
        </main>
      </body>
    </html>
  )
}
